### ISSUE TITLE
Text Indentation is not working

### ISSUE THREAD

**Issue by vikingsvivek** [dchenk/go-render-quill#4]
Hi, 
I am new to both quill and go-render-quill library. 
I am running examples to render quiil delta as HTML using go-render-quill.

For below delta, converted HTML is not rendered with same indentation.   

``[{"insert":"Hi NDNd"},{"attributes":{"indent":1},"insert":"\n"},{"attributes":{"underline":true,"italic":true,"bold":true},"insert":"nvn"},{"attributes":{"header":1},"insert":"\n"}]``

GO code

```
package main

import (
    "fmt"
	
    "github.com/dchenk/go-render-quill"
)

var ops = []byte(`[{"insert":"Hi NDNd"},{"attributes":{"indent":1},"insert":"\n"},{"attributes":{"underline":true,"italic":true,"bold":true},"insert":"nvn"},{"attributes":{"header":1},"insert":"\n"}]`)

func main() {
    html, err := quill.Render(ops)
    if err != nil {
        panic(err)
    }
    fmt.Println(string(html))
}
```

HTML generated by lib
`<p class="indent-1">Hi NDNd</p><h1><em><strong><u>nvn</u></strong></em></h1>`

HTML to render
```
<!DOCTYPE html>
<html>
<head>  
<title>Page Title</title>
<!-- Main Quill library -->
<script src="https://cdn.quilljs.com/1.1.3/quill.js"></script>
<script src="https://cdn.quilljs.com/1.1.3/quill.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- Theme included stylesheets -->
<link href="https://cdn.quilljs.com/1.1.3/quill.snow.css" rel="stylesheet">
<link href="https://cdn.quilljs.com/1.1.3/quill.bubble.css" rel="stylesheet">

<!-- Core build with no theme, formatting, non-essential modules -->
<link href="https://cdn.quilljs.com/1.1.3/quill.core.css" rel="stylesheet">


</head>
<body>
<div class="ql-editor">
<p class="indent-1">Hi NDNd</p><h1><em><strong><u>nvn</u></strong></em></h1>
</div>
</body>
</html>
```

Please suggest if I have missed something

**Comment by dchenk** [comment]
Hi and thanks for the question. It looks like this library is rendering the HTML properly. The thing here is that we do not insert actual tabs where a Delta has `"attributes":{"indent":1}`. We set `class="indent-1"` (or the appropriate `indent-#`) on the element, just as the Quill editor would with the same Delta. If the Quill editor produces Delta with the actual tab character `\t` in an `insert`, then it gets rendered as an actual tab.

So if you run `go-render-quill` with the following Delta: `[{"insert":"hello\n\tthi"},{"attributes":{"italic":true},"insert":"ss"},{"insert":"\nis\n"},{"attributes":{"bold":true},"insert":"quill"},{"insert":"\n"}]` you get: `<p>hello</p><p>	thi<em>ss</em></p><p>is</p><p><strong>quill</strong></p>`
which has the literal tab character as you're expecting. ([example](https://play.golang.org/p/vnidIixkh_d))

Closing this issue because it's resolved here. Let me know if you need further help.

**Comment by vikingsvivek** [comment]
Hi @dchenk , I tried generating HTML from quill editor for this delta.
`{"ops":[{"insert":"Hi NDNd"},{"attributes":{"indent":1},"insert":"\n"},{"attributes":{"underline":true,"italic":true,"bold":true},"insert":"nvn"},{"attributes":{"header":1},"insert":"\n"}]}`

and generated HTML got through quill.root.innerHTML is 
`<p class="ql-indent-1">Hi NDNd</p><h1><strong><em><u>nvn</u></em></strong></h1>`

Only the css class tagged at <p> tag is different in HTML generated for both cases.  When I changed the css class to ql-indent-1 manually, html rendered expected format.

**Comment by dchenk** [comment]
Hello. This library isn’t intended to render HTML with all the same CSS classes that the Quill editor uses, primarily because there is no official documentation in which the Quill editor is committed to not changing the CSS classes that are currently used. So if the Quill editor starts using other classes someday, will you suggest that this library change too? Doesn’t seem like it’d be worth tracking internal Quill implementation this way.

That said, you can easily, when defining your CSS, give the same set of properties to both “ql-indent-1” and “indent-1” like so:
```
.ql-indent-1, .indent-1 {
  font-size: 14px;
  text-indent: 8px;
}
```
